spring.application.name=SpringAIDemo
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.api-key=${OPENAI_API_KEY:<YOUR_OPENAI_API_KEY>}
spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.datasource.url=jdbc:mariadb://localhost:3307/spring_ai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


spring.ai.vectorstore.mariadb.initialize-schema=true

spring.main.allow-bean-definition-overriding=true

<!-- Optional: add to `src/main/resources/application.properties` -->
# ensure swagger UI path (defaults usually work, but explicit helps)
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
