spring.application.name=mcp
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.api-key=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

##
#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

spring.ai.mcp.client.sse.connection.spring-ai-mcp-server.enabled=true
spring.ai.mcp.client.sse.connections.spring-ai-mcp-server.url=http://localhost:8282
