spring.application.name=mcp
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.api-key=${OPENAI_API_KEY:<YOUR_OPENAI_API_KEY>}

##
#spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

spring.ai.mcp.client.sse.connection.spring-ai-mcp-server.enabled=true
spring.ai.mcp.client.sse.connections.spring-ai-mcp-server.url=http://localhost:8282
